
name: shell

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'NetBSD release'
        required: true
        type: choice
        options:
        - '10.0'
        - '9.4'
        - '9.3'
        - '9.2'
        - '9.1'
        - '9.0'
        default: '10.0'

jobs:
  runshell:
    runs-on: ubuntu-22.04
    name: Start a netbsd shell
    steps:
    - name: Starting a netbsd VM, please wait. It may take 3 minutes
      id: shell
      uses: vmactions/netbsd-vm@main
      with:
        release: ${{ github.event.inputs.release || '10.0' }}
        nat: |
          "8000": "80"
        envs: 'TestingDomain TEST_PREFERRED_CHAIN TEST_ACME_Server INPUT_*'
        sync: sshfs
        prepare: |
          pkg_add curl
        run: |
          pwd
          ls -lah
          whoami
          env
          uname -a
    - name: Sleep
      run: for i in $(seq 1 10) ; do echo $i; sleep 1; done
    - uses: neilpang/debugger-action@master

